In [97]:
import numpy as np
import pandas as pd

In [109]:
df = pd.read_csv("cleaned_zomato.csv")

In [119]:
df.head()

,id,delivery_person_id,delivery_person_age,delivery_person_ratings,distance_km,order_date,time_ordered,time_order_picked,weather_conditions,road_traffic_density,...,type_of_vehicle,multiple_deliveries,festival,city,time_taken_min,day_of_the_week,is_weekend,rating_category,time_of_the_day,distance_bucket
0,0xcdcd,DEHRES17DEL01,36.0,4.2,10.3,2022-02-12,21.55,22.10,Fog,Jam,...,Motorcycle,3.0,No,Metropolitian,46,Saturday,1,4.0,Night,Long
1,0xd987,KOCRES16DEL01,21.0,4.7,6.2,2022-02-13,14.55,15.05,Stormy,High,...,Motorcycle,1.0,No,Metropolitian,23,Sunday,1,5.0,Afternoon,Medium
2,0x2784,PUNERES13DEL03,23.0,4.7,13.8,2022-03-04,17.30,17.40,Sandstorms,Medium,...,Scooter,1.0,No,Metropolitian,21,Friday,0,5.0,Evening,Long
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,2.9,2022-02-13,9.20,9.30,Sandstorms,Low,...,Motorcycle,0.0,No,Metropolitian,20,Sunday,1,4.0,Morning,Short
4,0xdb64,KNPRES14DEL02,24.0,4.7,19.4,2022-02-14,19.50,20.05,Fog,Jam,...,Scooter,1.0,No,Metropolitian,41,Monday,0,5.0,Evening,Very Long

In [111]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["day_of_the_week"] = df["order_date"].dt.day_name()

**Finding day of the week from ordered_date**

In [112]:
df["is_weekend"] = np.where((df["day_of_the_week"]=="Saturday")|(df["day_of_the_week"]=="Sunday"), 1, 0)

**Checking if its a weekend or not for analyzing the performance at weeekend**

In [113]:
df["rating_category"] = round(df["delivery_person_ratings"])

**standardizing the rating for comaprison**

In [114]:
df

,id,delivery_person_id,delivery_person_age,delivery_person_ratings,distance_km,order_date,time_ordered,time_order_picked,weather_conditions,road_traffic_density,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city,time_taken_min,day_of_the_week,is_weekend,rating_category
0,0xcdcd,DEHRES17DEL01,36.0,4.2,10.28,2022-02-12,21.55,22.10,Fog,Jam,2,Snack,Motorcycle,3.0,No,Metropolitian,46,Saturday,1,4.0
1,0xd987,KOCRES16DEL01,21.0,4.7,6.24,2022-02-13,14.55,15.05,Stormy,High,1,Meal,Motorcycle,1.0,No,Metropolitian,23,Sunday,1,5.0
2,0x2784,PUNERES13DEL03,23.0,4.7,13.79,2022-03-04,17.30,17.40,Sandstorms,Medium,1,Drinks,Scooter,1.0,No,Metropolitian,21,Friday,0,5.0
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,2.93,2022-02-13,9.20,9.30,Sandstorms,Low,0,Buffet,Motorcycle,0.0,No,Metropolitian,20,Sunday,1,4.0
4,0xdb64,KNPRES14DEL02,24.0,4.7,19.40,2022-02-14,19.50,20.05,Fog,Jam,1,Snack,Scooter,1.0,No,Metropolitian,41,Monday,0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45488,0x7c09,JAPRES04DEL01,30.0,4.8,1.49,2022-03-24,11.35,11.45,Windy,High,1,Meal,Motorcycle,0.0,No,Metropolitian,32,Thursday,0,5.0
45489,0xd641,AGRRES16DEL01,21.0,4.6,11.01,2022-02-16,19.55,20.10,Windy,Jam,0,Buffet,Motorcycle,1.0,No,Metropolitian,36,Wednesday,0,5.0
45490,0x4f8d,CHENRES08DEL03,30.0,4.9,4.66,2022-03-11,23.50,0.05,Cloudy,Low,1,Drinks,Scooter,0.0,No,Metropolitian,16,Friday,0,5.0
45491,0x5eee,COIMBRES11DEL01,20.0,4.7,6.23,2022-03-07,13.35,13.40,Cloudy,High,0,Snack,Motorcycle,1.0,No,Metropolitian,26,Monday,0,5.0
45492,0x5fb2,RANCHIRES09DEL02,23.0,4.9,12.07,2022-03-02,17.10,17.15,Fog,Medium,2,Snack,Scooter,1.0,No,Metropolitian,36,Wednesday,0,5.0

In [115]:
def get_time_of_the_day(time):
    if pd.isna(time):
        return np.nan
    elif 5 <= time < 12 :
        return "Morning"
    elif 12<= time < 17:
        return "Afternoon"
    elif 17 <= time < 21:
        return "Evening"
    else:
        return "Night"

df["time_of_the_day"] = df["time_ordered"].apply(get_time_of_the_day)

**Can understand which timing has more orders**

In [116]:
def get_distance_bucket(dist):
    if pd.isna(dist):
        return np.nan
    elif dist < 5:
        return "Short"
    elif 5 <= dist < 10:
        return "Medium"
    elif 10 <= dist < 15:
        return "Long"
    else:
        return "Very Long"


df["distance_bucket"] = df["distance_km"].apply(get_distance_bucket)

**For finding range of deliveries**

In [118]:
df.to_csv("zomato_dataset_Engineered.csv",index = False)